"""
Qt widget for inspecting translated p-code operations.

This widget displays the p-code ops generated by the PcodeTranslator
in a tabular format, useful for debugging the translation layer.
"""

from __future__ import annotations

import logging
from typing import Optional

from .models import PcodeOp

logger = logging.getLogger(__name__)

try:
    from PySide6 import QtCore, QtGui, QtWidgets
    QT_AVAILABLE = True
except ImportError:
    try:
        from PyQt5 import QtCore, QtGui, QtWidgets
        QT_AVAILABLE = True
    except ImportError:
        QT_AVAILABLE = False


if QT_AVAILABLE:

    class PcodeViewerWidget(QtWidgets.QWidget):
        """
        Dock widget displaying translated p-code ops.

        Layout:
        ┌───────────────────────────────────────────┐
        │ [function name]                           │
        ├───────┬──────┬────────┬───────────────────┤
        │  VA   │ Order│ Opcode │ Operands          │
        ├───────┼──────┼────────┼───────────────────┤
        │ 401000│  1   │ COPY   │ rax = #0x0:8      │
        │ 401003│  2   │ INT_ADD│ u1 = rax + #0x1:8 │
        │ 401006│  3   │ COPY   │ rax = u1          │
        └───────┴──────┴────────┴───────────────────┘
        """

        def __init__(self, vw, vwgui, parent=None):
            super().__init__(parent)
            self.vw = vw
            self.vwgui = vwgui
            self._ops: list[PcodeOp] = []

            self._build_ui()
            self.setWindowTitle("P-Code Viewer")

        def _build_ui(self):
            layout = QtWidgets.QVBoxLayout(self)

            # Header
            self.func_label = QtWidgets.QLabel("No p-code loaded")
            self.func_label.setStyleSheet("font-weight: bold; font-size: 14px; padding: 4px;")
            layout.addWidget(self.func_label)

            # P-code table
            self.table = QtWidgets.QTableWidget()
            self.table.setColumnCount(4)
            self.table.setHorizontalHeaderLabels(["VA", "Order", "Opcode", "Operands"])
            self.table.horizontalHeader().setStretchLastSection(True)
            layout.addWidget(self.table)

            # Export button
            btn_layout = QtWidgets.QHBoxLayout()
            self.export_btn = QtWidgets.QPushButton("Export JSON")
            self.export_btn.clicked.connect(self._on_export)
            btn_layout.addWidget(self.export_btn)
            btn_layout.addStretch()
            layout.addLayout(btn_layout)

        def set_pcode(self, ops: list[PcodeOp], func_name: str = "") -> None:
            """Display a list of p-code ops in the table."""
            self._ops = ops
            self.func_label.setText(func_name or f"{len(ops)} ops")

            self.table.setRowCount(len(ops))
            for i, op in enumerate(ops):
                self.table.setItem(i, 0, QtWidgets.QTableWidgetItem(f"0x{op.va:08x}"))
                self.table.setItem(i, 1, QtWidgets.QTableWidgetItem(str(op.order)))
                self.table.setItem(i, 2, QtWidgets.QTableWidgetItem(op.opcode.value))

                # Format operands
                parts = []
                if op.output:
                    parts.append(f"{op.output} =")
                parts.append(op.opcode.value)
                if op.inputs:
                    parts.append("(" + ", ".join(str(v) for v in op.inputs) + ")")
                self.table.setItem(i, 3, QtWidgets.QTableWidgetItem(" ".join(parts)))

        def set_error(self, error_msg: str) -> None:
            """Display an error message."""
            self.func_label.setText("Error")
            self.table.setRowCount(1)
            self.table.setItem(0, 0, QtWidgets.QTableWidgetItem(error_msg))

        def _on_export(self) -> None:
            """Export the current p-code to a JSON file."""
            if not self._ops:
                return

            filename, _ = QtWidgets.QFileDialog.getSaveFileName(
                self, "Export P-Code", "", "JSON Files (*.json)"
            )
            if filename:
                import json
                data = [op.to_dict() for op in self._ops]
                with open(filename, 'w') as f:
                    json.dump(data, f, indent=2)

else:
    # Stub class for headless environments without Qt
    class PcodeViewerWidget:
        """Stub — Qt not available."""
        def __init__(self, *args, **kwargs):
            raise ImportError("PySide6 or PyQt5 is required for PcodeViewerWidget")